# Generated by Django 4.2.14 on 2024-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_options_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_time',
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_time_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время рассылки конец'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время рассылки начало'),
        ),
    ]
