# Generated by Django 4.2.14 on 2024-08-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailinglog_answer_alter_mailinglog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='message',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mail', verbose_name='рассылка'),
        ),
    ]
