# Generated by Django 4.2.14 on 2024-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_mailinglog_message_mailinglog_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='next_time_mailing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующее время расслыки'),
        ),
    ]
